# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'B:\Projects\MyProject\general.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget


class Ui_General(object):
    def setupUi(self, General):
        General.setObjectName("General")
        General.resize(866, 598)
        self.centralwidget = QtWidgets.QWidget(General)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.curr_move_title = QtWidgets.QLabel(self.centralwidget)
        self.curr_move_title.setObjectName("curr_move_title")
        self.gridLayout.addWidget(self.curr_move_title, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.fir_speed_label = QtWidgets.QLabel(self.centralwidget)
        self.fir_speed_label.setObjectName("fir_speed_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fir_speed_label)
        self.fir_speed_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.fir_speed_edit.setObjectName("fir_speed_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fir_speed_edit)
        self.acceleration_label = QtWidgets.QLabel(self.centralwidget)
        self.acceleration_label.setObjectName("acceleration_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.acceleration_label)
        self.acceleration_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.acceleration_edit.setObjectName("acceleration_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.acceleration_edit)
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setObjectName("time_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.time_label)
        self.time_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.time_edit.setObjectName("time_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.time_edit)
        self.gridLayout.addLayout(self.formLayout, 4, 3, 1, 2)
        self.gr_label = QtWidgets.QLabel(self.centralwidget)
        self.gr_label.setObjectName("gr_label")
        self.gridLayout.addWidget(self.gr_label, 0, 3, 1, 1)
        self.back_to_moves = QtWidgets.QPushButton(self.centralwidget)
        self.back_to_moves.setObjectName("back_to_moves")
        self.gridLayout.addWidget(self.back_to_moves, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_2.addWidget(self.create_btn)
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout_2.addWidget(self.clear_btn)
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_2.addWidget(self.delete_btn)
        self.on_gr_btn = QtWidgets.QPushButton(self.centralwidget)
        self.on_gr_btn.setObjectName("on_gr_btn")
        self.horizontalLayout_2.addWidget(self.on_gr_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 5)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 3, 3)
        self.curr_body_title = QtWidgets.QLabel(self.centralwidget)
        self.curr_body_title.setObjectName("curr_body_title")
        self.gridLayout.addWidget(self.curr_body_title, 3, 3, 1, 1)
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 2, 3, 1, 1)
        General.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(General)
        self.statusBar.setObjectName("statusBar")
        General.setStatusBar(self.statusBar)

        self.retranslateUi(General)
        QtCore.QMetaObject.connectSlotsByName(General)

    def retranslateUi(self, General):
        _translate = QtCore.QCoreApplication.translate
        General.setWindowTitle(_translate("General", "Основное окно"))
        self.curr_move_title.setText(_translate("General", "название текушего движения"))
        self.fir_speed_label.setText(_translate("General", "начальная скорость"))
        self.acceleration_label.setText(_translate("General", "ускорение"))
        self.time_label.setText(_translate("General", "время"))
        self.gr_label.setText(_translate("General", "график зависимости скороости от времени"))
        self.back_to_moves.setText(_translate("General", "сменить меню"))
        self.create_btn.setText(_translate("General", "создать"))
        self.clear_btn.setText(_translate("General", "очистить"))
        self.delete_btn.setText(_translate("General", "удалить"))
        self.on_gr_btn.setText(_translate("General", "показать на графике"))
        self.curr_body_title.setText(_translate("General", "название текущего тела"))
